spring:
   profiles:
      active: dev-6633
      
---
server:
   port: 6633
   
   
spring:
   profiles: dev-6633
   application:
      name: user-server
      
   datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/snack_product?useUnicode=true&serverTimezone=GMT&characterEncoding=utf8&useSSL=true
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: 123456
   http:
      encoding:
         charset: utf-8
         force: true
         enabled: true
         
   mail:
      protocol: smtp
      username: 1079210360@qq.com
      password: ppixvexfiulejjci
      port: 465
      host: smtp.qq.com
      properties:
         mail:
            smtp:
               auth: true
               timeout: 2500
               ssl:
                  enable: true
         
mybatis:
   #mapper映射文件在的路径
   mapper-locations: classpath:mapper/*Mapper.xml
   # 需要启动别名的类所在的包
   type-aliases-package: com.zky.snack.product.bean        
      
      
      
eureka:
   client:
      service-url:
         defaultZone: http://zhangkongyang:123456@127.0.0.1:6611/eureka        
   